### ISSUE TITLE
When I render with the CPU mode, it reports an error. please help

### ISSUE THREAD

**Issue by swrainbow** [hsimpson/ts-raytracer#29]
![image](https://github.com/hsimpson/ts-raytracer/assets/22050758/d9db88ae-593a-406b-85fe-ba039e8277cc)

 world: serialize(HittableList, world) -----------  wrong with here

**Comment by swrainbow** [comment]
![image](https://github.com/hsimpson/ts-raytracer/assets/22050758/8cdd0a84-5562-43fd-8f02-4f256dad5efe)
I need to take some time to figure out what the problem is. Most likely, it's a problem with serialization.

**Comment by hsimpson** [comment]
CPU mode is broken at the moment. I have a plan to remove the CPU mode completely, but this is a hobby project so at the moment I have no time and passion for it.
